name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI (via npx)
        run: npx supabase@latest --version

      - name: Deploy Supabase Edge Function
        run: |
          npx supabase functions deploy send-invite \
            --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} \
            --access-token ${{ secrets.SUPABASE_ACCESS_TOKEN }}
